name: CI

on:
  push:
    branches: [ master, demo ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  terraform:
    environment: Azure # Name of Env in GitHub Actions so I can reference specific vars
    runs-on: ubuntu-latest

    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v1

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate
      
      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve \
            -var "client_id=${{ secrets.CLIENT_ID }}" \
            -var "client_secret=${{ secrets.CLIENT_SECRET }}" \
            -var "tenant_id=${{ secrets.TENANT_ID }}" \
            -var "subscription_id=${{ secrets.SUBSCRIPTION_ID }}"

      - name: Terraform Show
        run: terraform show
