name: CI

on:
  push:
    branches: [ master, demo ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  terraform:
    environment: Azure # Name of Env in GitHub Actions so I can reference specific vars
    runs-on: ubuntu-latest

    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v1

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate -no-color
      
      # - name: Terraform Plan
      #   if: github.event_name == 'pull_request'
      #   run: terraform plan -no-color
      #   continue-on-error: true

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve \
            -var "client_id=$CLIENT_ID" \
            -var "client_secret=$CLIENT_SECRET" \
            -var "tenant_id=$TENANT_ID" \
            -var "subscription_id=$SUBSCRIPTION_ID" \
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          TENANT_ID: ${{ secrets.TENANT_ID }}
          SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}

      - name: Terraform Show
        run: terraform show

      # - name: Create Azure Credentials File
      #   run: |
      #     sudo touch ~/.azure/credentials
      #     sudo chmod 777 ~/.azure/credentials
      #     sudo echo "$CREDS" > ~/.azure/credentials
      #   env:
      #     CREDS: ${{ secrets.AZURE_CREDS_INI }}
